# Generated by Django 4.2.7 on 2023-11-09 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('announcement_title', models.CharField(max_length=40)),
                ('announcement_contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForEmailChk',
            fields=[
                ('chk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('chk_num', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inquiry_title', models.CharField(max_length=40)),
                ('inquiry_content', models.CharField(max_length=800)),
                ('is_open', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userdata')),
            ],
        ),
    ]
