# Generated by Django 4.2.7 on 2023-11-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureInfo',
            fields=[
                ('lecture_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=40)),
                ('appropriate_grade', models.CharField(max_length=5)),
                ('platform', models.CharField(max_length=20)),
                ('lecture_infomation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalCategories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('degree', models.IntegerField()),
                ('top_category_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainPostApp.totalcategories')),
            ],
        ),
        migrations.CreateModel(
            name='LectureReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_contents', models.CharField(blank=True, max_length=200, null=True)),
                ('review_star', models.IntegerField()),
                ('review_date', models.DateTimeField()),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPostApp.lectureinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='LectureCategories',
            fields=[
                ('lecture_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPostApp.totalcategories')),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPostApp.lectureinfo')),
            ],
        ),
    ]
