# Generated by Django 4.2.7 on 2023-11-09 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainPostApp', '0001_initial'),
        ('userPostApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('Favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPostApp.usercommunitypost')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteLectures',
            fields=[
                ('Favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPostApp.lectureinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCategories',
            fields=[
                ('Favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPostApp.totalcategories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userdata')),
            ],
        ),
    ]
