# Generated by Django 4.2.7 on 2023-11-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPostApp', '0003_alter_lecturecategories_category_id_and_more'),
        ('Favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecategories',
            name='category_id',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='mainPostApp.totalcategories'),
        ),
    ]
